spring:
  application:
    name: code-challenge

#springdoc:
#  api-docs:
#    groups:
#      enabled: true
#    path: /swagger-doc/v3/api-docs
#  swagger-ui:
#    path: /swagger-doc/swagger-ui.html



